// This file is part of NextMed Patient Registry
// Copyright (C) 2026 NextMed Team
// SPDX-License-Identifier: Apache-2.0

/**
 * Witness Implementation for Patient Registry Contract
 *
 * Pattern derived from verified reference: PaimaStudios/midnight-game-2
 *
 * Witnesses provide private/off-chain data to ZK circuits. They:
 * 1. Take a WitnessContext<Ledger, PrivateState> as first argument
 * 2. Return a tuple [newPrivateState, returnValue]
 * 3. Never leave the user's device - only the ZK proof is submitted
 */

import type { WitnessContext } from "@midnight-ntwrk/compact-runtime";
import { createHash } from "node:crypto";

// Import the Ledger type from the compiled contract
// This is generated by the Compact compiler
import * as PatientRegistryContract from "./managed/patient-registry/contract/index.js";

/**
 * Ledger type alias for the patient registry contract
 * Represents the on-chain public state
 */
export type Ledger = ReturnType<typeof PatientRegistryContract.ledger>;

/**
 * Private state stored locally on the user's device
 * This data never leaves the device - only ZK proofs are submitted
 */
export type PatientRegistryPrivateState = {
  /** Secret key for authentication (32 bytes) */
  readonly secretKey: Uint8Array;
  /** Optional file hash for upload verification (32 bytes) */
  readonly fileHash?: Uint8Array;
  /** Optional patient data hash */
  readonly patientDataHash?: Uint8Array;
};

/**
 * Create initial private state
 * @param secretKey - 32-byte secret key for the user
 */
export const createPrivateState = (
  secretKey: Uint8Array,
): PatientRegistryPrivateState => ({
  secretKey,
});

/**
 * Create private state with file hash (for upload verification)
 * @param secretKey - 32-byte secret key for the user
 * @param fileHash - 32-byte hash of the medical file
 */
export const createPrivateStateWithFile = (
  secretKey: Uint8Array,
  fileHash: Uint8Array,
): PatientRegistryPrivateState => ({
  secretKey,
  fileHash,
});

/**
 * Compute file hash client-side
 * Uses SHA-256 to create a 32-byte hash of the file content
 * @param fileContent - Buffer containing the file data
 */
export const computeFileHash = (fileContent: Buffer): Uint8Array => {
  const hash = createHash("sha256").update(fileContent).digest();
  return new Uint8Array(hash);
};

/**
 * Witness implementations for the Patient Registry contract
 *
 * Each witness function:
 * - First parameter: WitnessContext<Ledger, PrivateState>
 * - Additional parameters: Match the Compact witness declaration
 * - Returns: [newPrivateState, returnValue]
 */
export const witnesses = {
  /**
   * Witness: local_secret_key
   *
   * Provides the user's secret key from private state
   * Used for authentication and key derivation
   *
   * @returns [privateState, secretKey as Uint8Array]
   */
  local_secret_key: ({
    privateState,
  }: WitnessContext<
    Ledger,
    PatientRegistryPrivateState
  >): [PatientRegistryPrivateState, Uint8Array] => {
    if (!privateState.secretKey) {
      throw new Error("No secret key found in private state");
    }
    return [privateState, privateState.secretKey];
  },

  /**
   * Witness: local_file_hash
   *
   * Provides the file hash from private state for upload verification
   * The actual file data never leaves the device - only this hash is used
   * in the ZK proof to verify integrity
   *
   * @returns [privateState, fileHash as Uint8Array]
   */
  local_file_hash: ({
    privateState,
  }: WitnessContext<
    Ledger,
    PatientRegistryPrivateState
  >): [PatientRegistryPrivateState, Uint8Array] => {
    if (!privateState.fileHash) {
      throw new Error(
        "No file hash stored in private state. Call createPrivateStateWithFile first.",
      );
    }
    return [privateState, privateState.fileHash];
  },
};

/**
 * Type assertion to ensure witnesses match expected signature
 */
export type WitnessSignature<ReturnType> = (
  context: WitnessContext<Ledger, PatientRegistryPrivateState>,
) => [PatientRegistryPrivateState, ReturnType];

// Re-export the Contract for convenience
export { PatientRegistryContract };
